default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ruby
  password: ruby
  host: localhost

development:
  <<: *default
  database: stoncks_dev

test:
  <<: *default
  database: stoncks_test